# Generated by Django 4.0.2 on 2022-07-20 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('interview_time', models.DateTimeField()),
                ('is_interviewed', models.BooleanField()),
                ('C', models.IntegerField()),
                ('CPP', models.IntegerField()),
                ('CHash', models.IntegerField()),
                ('Java', models.IntegerField()),
                ('Python', models.IntegerField()),
                ('Git', models.IntegerField()),
                ('OpenCV', models.IntegerField()),
                ('Arduino', models.IntegerField()),
                ('other_micro_controllers', models.CharField(max_length=100)),
                ('image_processing', models.IntegerField()),
                ('machine_learning', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('data_structures', models.IntegerField()),
                ('algorithms', models.IntegerField()),
                ('PCB_design_eagle', models.IntegerField()),
                ('PCB_design_altium', models.IntegerField()),
                ('PCB_design_proteus', models.IntegerField()),
                ('PCB_manufacture_single', models.IntegerField()),
                ('PCB_manufacture_double', models.IntegerField()),
                ('SMD', models.IntegerField()),
                ('projects', models.CharField(max_length=200)),
                ('sensors_knowledge', models.CharField(max_length=200)),
                ('GUI', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_data.member')),
            ],
        ),
    ]
